version: "3.9"
services:
  api:
    build: ./
    container_name: wa-api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - db
  worker:
    build: ./
    container_name: wa-worker
    env_file: .env
    command: ["python", "worker/worker.py"]
    volumes:
      - ./backend:/app
      - ./worker:/app/worker
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: wa-db
    environment:
      POSTGRES_USER: wa
      POSTGRES_PASSWORD: wa
      POSTGRES_DB: wa
    ports:
      - "5432:5432"
    volumes:
      - wa-db:/var/lib/postgresql/data
volumes:
  wa-db:
